verbose: False
debug: False

detector:
  lib: opencv #opencv or dlib
  opencv:
    model: haarcascade_frontalface_alt.xml
    scale_factor: 1.3
    min_neighbors: 5
    cuda: True

aligner:
  lib: dlib #dlib
  dlib: 
    model: shape_predictor_68_face_landmarks.dat
    image_dimension: 96

embosser:
  lib: facenet #facenet
  facenet:
    model: nn4.small2.v1.t7
    cuda: True

classifier:
  lib: sklearn #sklearn
  sklearn:
    model: classifier.pkl
    threshold: 0.5
