subscribers:

  camera_reading:
<<<<<<< HEAD
    topic: /kinect2/qhd/image_color_rect
=======
    topic: /vision_system/vsb/image_depth_raw
>>>>>>> master
    queue_size: 1
  
  classifier_reload:
    topic: /vision_system/fr/classifier_reload
    queue_size: 1

publishers:

  face_recognition:
    topic: /vision_system/fr/face_recognition
    queue_size: 1
<<<<<<< HEAD
  
  face_recognition3d:
    topic: /vision_system/fr/face_recognition3d
    queue_size: 1
=======
>>>>>>> master

  face_recognition_view:
    topic: /vision_system/fr/face_recognition_view
    queue_size: 1

  classifier_reload:
    topic: /vision_system/fr/classifier_reload
    queue_size: 1

services:

  image2world:
    service: /vision_system/iw/image2world

  classifier_training:
    service: /vision_system/fr/classifier_training